import React, { useEffect } from 'react';
import { Image, StyleSheet, Text, View } from 'react-native';
import Animated, {
  Easing,
  runOnJS,
  useAnimatedStyle,
  useSharedValue,
  withDelay,
  withRepeat,
  withSequence,
  withTiming,
} from 'react-native-reanimated';
import RunturfingLogo from './RunturfingLogo';
import { NEO, SPACING } from '../utils/theme';

/**
 * The launch screen, once React can paint. It takes over from the native
 * splash (assets/splash.png, generated by scripts/make-splash.mjs) which shows
 * the same mark on the same paper over the same riso ripple plate — so the
 * handover reads as one screen that gains a wordmark, not as two screens.
 *
 * The native splash cannot carry the wordmark: Android 12+ masks
 * windowSplashScreenAnimatedIcon to a circle, and anything as wide as
 * RUNTURFING loses its ends.
 *
 * Rendered with no props while fonts are still resolving, and with
 * `ready`/`onHidden` once the app tree is mounted behind it.
 */
type Props = {
  /** Stores hydrated and fonts settled. The screen holds until this is true. */
  ready?: boolean;
  /** Called after the fade finishes, so the caller can unmount this. */
  onHidden?: () => void;
};

// Long enough that a warm start does not flash the mark and vanish, short
// enough that it never feels like the app is stalling.
const MIN_HOLD_MS = 650;
const FADE_MS = 300;

export default function BrandSplash({ ready, onHidden }: Props) {
  const opacity = useSharedValue(1);
  const sweep = useSharedValue(0);

  useEffect(() => {
    sweep.value = withRepeat(
      withSequence(
        withTiming(1, { duration: 620, easing: Easing.inOut(Easing.quad) }),
        withTiming(0, { duration: 620, easing: Easing.inOut(Easing.quad) })
      ),
      -1,
      false
    );
  }, [sweep]);

  useEffect(() => {
    if (!ready || !onHidden) return;
    opacity.value = withDelay(
      MIN_HOLD_MS,
      withTiming(0, { duration: FADE_MS, easing: Easing.out(Easing.quad) }, (finished) => {
        if (finished) runOnJS(onHidden)();
      })
    );
  }, [ready, onHidden, opacity]);

  const fadeStyle = useAnimatedStyle(() => ({ opacity: opacity.value }));
  // The block runs the width of the track minus its own width, so it stops at
  // the inside of the ink border rather than sliding under it.
  const sweepStyle = useAnimatedStyle(() => ({
    transform: [{ translateX: sweep.value * (TRACK_WIDTH - BLOCK_WIDTH) }],
  }));

  return (
    <Animated.View style={[styles.container, fadeStyle]} pointerEvents="none">
      <View style={styles.mark}>
        {/* Same plate the intro finale runs behind the mark, and the same one
            baked into the native splash. */}
        <Image
          source={require('../../assets/texture-ripple.png')}
          style={styles.plate}
          resizeMode="contain"
        />
        <RunturfingLogo size={150} />
      </View>

      <View style={styles.wordmarkBlock}>
        <Text style={styles.wordmark}>RUNTURFING</Text>
      </View>

      <View style={styles.track}>
        <Animated.View style={[styles.block, sweepStyle]} />
      </View>
    </Animated.View>
  );
}

const TRACK_WIDTH = 148;
const BLOCK_WIDTH = 44;

const styles = StyleSheet.create({
  container: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: NEO.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mark: { alignItems: 'center', justifyContent: 'center' },
  // Kept quiet for the same reason as on the intro: the plate carries its own
  // cream paper, a shade warmer than our surface, and its square edge shows if
  // it is run any stronger.
  plate: { position: 'absolute', width: 250, height: 250, opacity: 0.32 },
  wordmarkBlock: {
    backgroundColor: NEO.ink,
    paddingHorizontal: 14,
    paddingVertical: 8,
    marginTop: SPACING.xl,
  },
  wordmark: { fontSize: 18, fontWeight: '900', color: NEO.surface, letterSpacing: 3 },
  track: {
    width: TRACK_WIDTH,
    height: 14,
    marginTop: SPACING.xl,
    borderWidth: 2,
    borderColor: NEO.ink,
    backgroundColor: NEO.white,
    justifyContent: 'center',
  },
  block: { width: BLOCK_WIDTH, height: '100%', backgroundColor: NEO.yellow },
});
